### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
Run gofumpt to fix formatting.
Add a few extra lines to be more legible.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
The code was inconsistent, I attempted to make it a bit more concise for my sanity.

**Review by dcermak — APPROVED** [review]
LGTM, but I'd suggest two additional steps (can be made in a later PR):
1. add the commit with the reformat to `{README,contributing}.md` mentioning the commit sha to omit it from blame
2. add the formater to the CI

**Comment by alexandrevicenzi** [comment]
@dcermak see my notes.

1. I'm ok with it, but I'm not sure if I understand what you want exactly, just a code styling guideline for newer contributions?
2. I have an upcoming PR with changes to the CI, and I plan to include gofumpt.

**Comment by dcermak** [comment]
> @dcermak see my notes.
> 
>     1. I'm ok with it, but I'm not sure if I understand what you want exactly, just a code styling guideline for newer contributions?

No, I meant to add something along the lines of:

> Note that commit 89987cf1ede28415d0fd2057184ea425ba29b509 is a commit that applies gofumpt. To omit it from `git blame` run `git blame --ignore-rev 89987cf1ede28415d0fd2057184ea425ba29b509`

**Pull request merged**
